# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)

1.18.1


#### 3. Create a null vector of size 10

In [5]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [3]:
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])
arr.size

6

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [12]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
z=np.arange(1,7)
z=z[::-1]
print(z)

[6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
l=np.arange(9).reshape(3,3)
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
z=[1,2,0,0,4,0]
m=len(z)
c=0
for i in z:
    c=c+1
    if i!=0:
        print(c)

1
2
5


#### 11. Create a 3x3 identity matrix

In [20]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [21]:
a=np.random.rand(3,3,3)
a

array([[[0.8853251 , 0.3320609 , 0.12399114],
        [0.63655131, 0.74671543, 0.3268038 ],
        [0.4030838 , 0.87658503, 0.71992134]],

       [[0.65302588, 0.77537009, 0.67215841],
        [0.69902455, 0.36555535, 0.58342749],
        [0.63188907, 0.23153055, 0.22369896]],

       [[0.03974985, 0.85127378, 0.31573748],
        [0.68399551, 0.48935343, 0.6611951 ],
        [0.25198272, 0.25641085, 0.54301604]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
a=np.random.rand(3,3)
print(a)
print(np.max(a))
print(np.min(a))

[[0.9723329  0.48700459 0.6187781 ]
 [0.18851692 0.92497967 0.67657295]
 [0.98074863 0.48863589 0.66466842]]
0.9807486265228883
0.18851692468722003


#### 14. Create a random vector of size 30 and find the mean value

In [26]:
a=np.random.rand(30)
print(a)
np.mean(a)

[8.34363452e-01 7.18046397e-01 3.80025823e-01 2.04728449e-02
 3.57583560e-01 9.83785745e-01 8.17027844e-02 6.82443668e-01
 8.31303559e-01 1.03098461e-01 4.72468478e-02 4.04205019e-01
 7.55512282e-01 3.87976556e-01 1.13707385e-02 6.15266464e-01
 9.79530535e-01 1.80044027e-02 7.04797959e-01 9.12927238e-01
 2.89059291e-04 1.87771537e-03 7.26135342e-01 1.42260772e-01
 8.74668699e-01 5.91743962e-01 2.44781015e-02 3.88257096e-01
 4.02365196e-01 4.61306961e-01]


0.4481015746848671

#### 15. Create a 2d array with 1 on the border and 0 inside

In [38]:
i,j=map(int,input().split())
z=np.ones((i,j))
z[1:-1,1:-1]=0
print(z)

3 3
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [52]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'int')
a[1:-1,1:-1]=0
print(a)

[[1 2 4]
 [5 8 7]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
nan
False
False
nan
False
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
a=np.diag(1+np.arange(4),k=-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
z=np.ones((8,8),dtype=int)
z[1::2,::2]=0  
z[::2,1::2]=0
print(z)    

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [53]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)
